# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v3.0
      with:
        # Name of the Docker image
        image: discord-bot/discord-bot
        # Tag override for Docker image
        tag: latest
        # Target Docker registry
        registry: docker.pkg.github.com
        # Location of Dockerfile, if not Dockerfile in root directory
        githubOrg: support-pp
        # Docker build arguments in format KEY=VALUE,KEY=VALUE
        # Docker registry username
        username: ${{ github.actor }}
        # Docker registry password
        password: ${{ secrets.GITHUB_TOKEN }} 
